SELECT 
    ADM_ID AS IP_NUMBER,  
    PAT_PCODE AS OPD_NUMBER,
    PAT_NAME AS FULL_NAME,
    (SELECT WRD_NAME FROM WARD WHERE WRD_ID_A = ADM_WRD_ID_A) AS WARD,
    PAT_SEX, PAT_AGE, PAT_ADDR, PAT_CITY
FROM ADMISSION JOIN PATIENT ON PAT_ID = ADM_PAT_ID
WHERE ADM_DELETED = 'N'
AND ADM_DATE_ADM >= '2014-01-01' AND ADM_DATE_ADM <= '2014-07-01'
ORDER BY  ADM_ID, OPD_NUMBER