SELECT ADM_ID AS IP_NUMBER, PAT_NAME AS FULL_NAME, PAT_PCODE AS OPD_NUMBER, ADM_DATE_DIS AS DATE_DISCHARGE, ADM_WRD_ID_A,
    (SELECT DIST_DESC FROM DISCHARGETYPE WHERE DIST_ID_A = ADM_DIST_ID_A) AS OUTCOME,
    IF ( ADM_WRD_ID_A = 'I' , IF(DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)=0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)), 0 ) AS MEDICAL,
    IF ( ADM_WRD_ID_A = 'M' , IF(DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)=0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)), 0 ) AS DELIVERY,
    IF ( ADM_WRD_ID_A = 'G' , IF(DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)=0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)), 0 ) AS GYNE,
    IF ( ADM_WRD_ID_A = 'O' , IF(DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)=0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)), 0 ) AS ORTHO,
    IF ( ADM_WRD_ID_A = 'S' , IF(DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)=0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)), 0 ) AS SURGICAL,
    IF ( ADM_WRD_ID_A = 'P' , IF(DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)=0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)), 0 ) AS PEDIATRICS,
    IF ( ADM_WRD_ID_A = 'N' , IF(DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)=0, 1, DATEDIFF(ADM_DATE_DIS, ADM_DATE_ADM)), 0 ) AS NEONATAL,    
    PAT_SEX, PAT_AGE,
    (SELECT DIS_DESC FROM DISEASE WHERE DIS_ID_A = ADM_OUT_DIS_ID_A) AS WHO_CODE
FROM ADMISSION
JOIN PATIENT 
ON PAT_ID = ADM_PAT_ID
WHERE 
    ADM_DATE_DIS != ' ' AND
    ADM_DATE_DIS >= '2014-01-01' AND ADM_DATE_DIS <= '2014-06-02'
    AND PAT_DELETED = 'N'
    AND ADM_WRD_ID_A != 'Q'
ORDER BY IP_NUMBER
