select OPD_ID, BLL_ID, OPD_PAT_ID, OPD_DATE, MDSR_CODE, MDSR_DESC,  BLL_AMOUNT,
       OPD_AGE, OPD_SEX, OPD_DIS_ID_A, OPD_DIS_ID_A_2, OPD_DIS_ID_A_3, OPD_PAT_CITY, MWPD_MDSR_ID, MWP_ID, MWP_DIS_ID_A
from MEDICALDSR
join  
(
select MWPD_MDSR_ID, MWP_ID, OPD_ID, BLL_ID, OPD_PAT_ID, OPD_DATE,  BLL_AMOUNT, OPD_AGE, OPD_SEX, OPD_DIS_ID_A, OPD_DIS_ID_A_2, OPD_DIS_ID_A_3, 
OPD_PAT_CITY, MWP_DIS_ID_A
from MEDICALDSRWARDPRESCRIPTIONDETAIL
join
(select MWP_ID, OPD_ID, BLL_ID, OPD_PAT_ID, OPD_DATE,  BLL_AMOUNT, OPD_AGE, OPD_SEX, OPD_DIS_ID_A, OPD_DIS_ID_A_2, OPD_DIS_ID_A_3, OPD_PAT_CITY,
MWP_DIS_ID_A
FROM 
MEDICALDSRWARDPRESCRIPTION 
join
(
select OPD_ID, BLL_ID, OPD_PAT_ID, OPD_DATE, BLL_AMOUNT, OPD_AGE, OPD_SEX, OPD_DIS_ID_A, OPD_DIS_ID_A_2, OPD_DIS_ID_A_3, OPD_PAT_CITY  from OPD
join BILLS 
on BLL_DATE = OPD_DATE and OPD_PAT_ID = BLL_ID_PAT
 WHERE DATE_FORMAT(OPD_DATE, '%Y-%m-&d') >= '2014-01-01' and DATE_FORMAT(OPD_DATE, '%Y-%m-&d') <= '2014-07-01' 
order by OPD_ID, OPD_PAT_ID
) as A
on BLL_ID = MWP_BLL_ID
) AS B
ON MWP_ID = MWPD_ID
) AS C
ON MDSR_ID= MWPD_MDSR_ID
order by OPD_PAT_ID, OPD_DATE
