UPDATE MENUITEM SET MNI_POSITION='0' WHERE MNI_ID_A='btnadmnew';
UPDATE MENUITEM SET MNI_POSITION='1' WHERE MNI_ID_A='btnadmedit';
UPDATE MENUITEM SET MNI_POSITION='3' WHERE MNI_ID_A='btnadmdel';
UPDATE MENUITEM SET MNI_POSITION='4' WHERE MNI_ID_A='btnadmadm';
UPDATE MENUITEM SET MNI_POSITION='5' WHERE MNI_ID_A='btnadmopd';
UPDATE MENUITEM SET MNI_POSITION='6' WHERE MNI_ID_A='btnadmbill';
UPDATE MENUITEM SET MNI_POSITION='7' WHERE MNI_ID_A='data';
UPDATE MENUITEM SET MNI_POSITION='8' WHERE MNI_ID_A='btnadmpatientfolder';
UPDATE MENUITEM SET MNI_POSITION='9' WHERE MNI_ID_A='btnadmtherapy';
UPDATE MENUITEM SET MNI_POSITION='10' WHERE MNI_ID_A='btnadmmer';

INSERT INTO MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION) VALUES ('btnadmemergency', 'angal.menu.btn.btnadmemergency', 'angal.menu.btnadmemergency', 'x', 'E', 'admission', 'none', 'N', '2');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin', 'btnadmemergency', 'Y');