ALTER TABLE DISEASE ADD COLUMN DIS_IPD_OUT_INCLUDE INT(11) NOT NULL DEFAULT '0' AFTER DIS_IPD_IN_INCLUDE, CHANGE COLUMN DIS_IPD_INCLUDE DIS_IPD_IN_INCLUDE INT(11) NOT NULL DEFAULT '0';

UPDATE DISEASE SET DIS_IPD_OUT_INCLUDE = 1 WHERE DIS_ID_A REGEXP '[0-9][0-9.]*[0-9]' AND (DIS_OPD_INCLUDE <> 0 AND DIS_IPD_IN_INCLUDE <> 0);
UPDATE DISEASE SET DIS_OPD_INCLUDE = 0 WHERE DIS_ID_A NOT REGEXP '[0-9][0-9.]*[0-9]';