-- TIMESTAMP FROM BILLS
-- SELECT PAT_TIMESTAMP, BLL_ID_PAT, BLL_DATE
-- FROM PATIENT JOIN (SELECT * FROM BILLS GROUP BY BLL_ID_PAT ORDER BY BLL_DATE ASC) AS BILLS ON PAT_ID = BLL_ID_PAT
-- WHERE PAT_ID > 0
-- AND PAT_TIMESTAMP = 0;

UPDATE PATIENT 
JOIN (SELECT * FROM BILLS GROUP BY BLL_ID_PAT ORDER BY BLL_DATE ASC) AS BILLS ON PAT_ID = BLL_ID_PAT
SET PAT_TIMESTAMP = BLL_DATE
WHERE PAT_ID > 0
AND PAT_TIMESTAMP = 0;

-- TIMESTAMP FROM OPD
-- SELECT PAT_TIMESTAMP, OPD_DATE
-- FROM PATIENT JOIN (SELECT * FROM OPD GROUP BY OPD_PAT_ID ORDER BY OPD_DATE ASC) AS OPDS ON PAT_ID = OPD_PAT_ID
-- WHERE PAT_ID > 0
-- AND PAT_TIMESTAMP = 0;

UPDATE PATIENT 
JOIN (SELECT * FROM OPD GROUP BY OPD_PAT_ID ORDER BY OPD_DATE ASC) AS OPDS ON PAT_ID = OPD_PAT_ID
SET PAT_TIMESTAMP = OPD_DATE
WHERE PAT_ID > 0
AND PAT_TIMESTAMP = 0;

-- BDATE FROM AGETYPE
-- SELECT PAT_TIMESTAMP, PAT_BDATE, PAT_AGE, PAT_AGETYPE, substring(PAT_AGETYPE, LOCATE('/', PAT_AGETYPE)+1) AS MONTHS, DATE((date_sub(PAT_TIMESTAMP, INTERVAL substring(PAT_AGETYPE, LOCATE('/', PAT_AGETYPE)+1) MONTH))) AS BDATE 
-- FROM PATIENT
-- WHERE PAT_TIMESTAMP > 0
-- AND PAT_ID > 0
-- AND PAT_AGETYPE NOT LIKE "" 
-- AND PAT_BDATE IS NULL;

UPDATE PATIENT SET PAT_BDATE = DATE((date_sub(PAT_TIMESTAMP, INTERVAL substring(PAT_AGETYPE, LOCATE('/', PAT_AGETYPE)+1) MONTH))), PAT_AGETYPE = ""
WHERE PAT_TIMESTAMP > 0
AND PAT_ID > 0
AND PAT_AGETYPE NOT LIKE "" 
AND PAT_BDATE IS NULL;

-- BDATE FROM AGE
-- SELECT PAT_TIMESTAMP, PAT_BDATE, PAT_AGE, DATE(date_sub(PAT_TIMESTAMP, INTERVAL PAT_AGE YEAR)) AS BDATE
-- FROM PATIENT
-- WHERE PAT_TIMESTAMP > 0
-- AND PAT_ID > 0
-- AND PAT_BDATE IS NULL;

UPDATE PATIENT SET PAT_BDATE = DATE(date_sub(PAT_TIMESTAMP, INTERVAL PAT_AGE YEAR))
WHERE PAT_TIMESTAMP > 0
AND PAT_ID > 0
AND PAT_BDATE IS NULL;

-- AGE FROM BDATE
-- SELECT PAT_TIMESTAMP, PAT_BDATE, PAT_AGE, PAT_AGETYPE, TIMESTAMPDIFF(YEAR, PAT_BDATE, CURDATE()) AS AGE
-- FROM PATIENT
-- WHERE PAT_TIMESTAMP > 0
-- AND PAT_ID > 0
-- AND PAT_BDATE IS NOT NULL;

UPDATE PATIENT SET PAT_AGE = TIMESTAMPDIFF(YEAR, PAT_BDATE, CURDATE())
WHERE PAT_TIMESTAMP > 0
AND PAT_ID > 0
AND PAT_BDATE IS NOT NULL;