DELETE FROM MALNUTRITIONCONTROL;
ALTER TABLE MALNUTRITIONCONTROL AUTO_INCREMENT = 1;

-- Extend MALNUTRITIONCONTROL table
ALTER TABLE MALNUTRITIONCONTROL 
ADD COLUMN MLN_TYPE 			VARCHAR(20) NOT NULL 				,
ADD COLUMN MLN_EXT_CODE			VARCHAR(20) 						,
ADD COLUMN MLN_DATE_CREATED 	DATETIME 	NOT NULL 				,
ADD COLUMN MLN_LAST_UPDATED 	DATETIME 	NOT NULL 				,
ADD COLUMN MLN_DATE_VIS 		DATETIME 							,
ADD COLUMN MLN_US_ID_A 			VARCHAR(20) NOT NULL 				,
ADD COLUMN MLN_PAT_AGE 			INT(11) 							,
ADD COLUMN MLN_MIN_WEIGHT 		VARCHAR(20) 		 				,
ADD COLUMN MLN_MIN_WEIGHT_DATE 	DATETIME 							,
ADD COLUMN MLN_MUAC 			FLOAT								,
ADD COLUMN MLN_WH 				INT(3) NULL							,
ADD COLUMN MLN_OEDEMA 			INT(1) NULL							,
ADD COLUMN MLN_RELAPSE 			BOOLEAN								,
ADD COLUMN MLN_KM				VARCHAR(2)							,
ADD COLUMN MLN_READMISSION 		BOOLEAN								,
ADD COLUMN MLN_REFERRED_BY 		VARCHAR(100)						,
ADD COLUMN MLN_OUTCOME 			VARCHAR(20) 						,
ADD COLUMN MLN_TB				BOOLEAN								,
ADD COLUMN MLN_HIV 				VARCHAR(1) DEFAULT 'U'      		,
ADD COLUMN MLN_SEPSIS			BOOLEAN                     		,
ADD COLUMN MLN_ANAEMIA			BOOLEAN								,
ADD COLUMN MLN_PNEUMONIA		BOOLEAN								,
ADD COLUMN MLN_MALARIA			BOOLEAN								,
ADD COLUMN MLN_CP 				BOOLEAN								,
ADD COLUMN MLN_RICKETTS			BOOLEAN								,
ADD COLUMN MLN_OTHER			BOOLEAN								,
ADD COLUMN MLN_REMARKS			VARCHAR(200) 						,
ADD COLUMN MLN_FOLLOWUP			BOOLEAN								,
ADD COLUMN MLN_CLOSEST_HC		VARCHAR(50) 						,
ADD COLUMN MLN_FROM_OTHER_OTP 	BOOLEAN								,
ADD COLUMN MLN_FROM_OTHER_TFP 	BOOLEAN								,
ADD COLUMN MLN_TO_OTHER_TFP 	BOOLEAN								,
ADD COLUMN MLN_MEDICAL_TRASNFER	BOOLEAN								,
ADD COLUMN MLN_DATE_DELETED 	DATETIME NULL 						,
ADD COLUMN MLN_PAT_PCODE	 	VARCHAR(10) 						,
ADD COLUMN MLN_PAT_NAME		 	VARCHAR(100) 						,
ADD COLUMN MLN_PAT_GENDER 		CHAR(1) 							,
ADD COLUMN MLN_PAT_MONTHS	 	VARCHAR(20) 						,
ADD COLUMN MLN_PAT_CITY		 	VARCHAR(50) 						,
ADD COLUMN MLN_PAT_ADDR		 	VARCHAR(50)                 		,
CHANGE COLUMN MLN_DATE_SUPP MLN_DATE_SUPP DATETIME NULL DEFAULT NULL,
CHANGE COLUMN MNL_DATE_CONF MLN_DATE_CONF DATETIME NULL DEFAULT NULL;

UPDATE MALNUTRITIONCONTROL SET MLN_DATE_CREATED = MLN_DATE_CONF, MLN_LAST_UPDATED = MLN_DATE_CONF, MLN_DATE_VIS = MLN_DATE_CONF
WHERE MLN_DATE_CREATED IS NULL;

UPDATE ADMISSION SET ADM_TYPE = 'N' WHERE ADM_TYPE in ('P', 'M');

ALTER TABLE MALNUTRITIONCONTROL
ADD CONSTRAINT FK_MLN_US_ID_A FOREIGN KEY (MLN_US_ID_A) REFERENCES USER (US_ID_A)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_MLN_ADM_ID FOREIGN KEY (MLN_ADM_ID) REFERENCES ADMISSION (ADM_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE MALNUTRITIONCONTROL
  DROP INDEX MLN_ADM_ID,
  ADD INDEX FK_MLN_US_ID_A (MLN_US_ID_A ASC),
  ADD INDEX FK_MLN_ADM_ID (MLN_ADM_ID ASC);

