CREATE  TABLE MEDICALDSRWARDMISSING (
  WMS_ID INT(10) NOT NULL AUTO_INCREMENT ,
  WMS_DATE DATETIME NOT NULL ,
  WMS_WRD_ID_A CHAR(1) NOT NULL ,
  WMS_MDSR_ID VARCHAR(100) NOT NULL ,
  WMS_MDSR_QTY FLOAT NOT NULL ,
  WMS_MSDR_UNITS VARCHAR(10) NOT NULL ,
  PRIMARY KEY (WMS_ID)
);