ALTER TABLE OPD 
ADD COLUMN OPD_WRD_ID_A CHAR(1) NOT NULL DEFAULT 'D' AFTER OPD_CHECKED,
ADD INDEX FK_OPD_WARD_IDX (OPD_WRD_ID_A ASC);

ALTER TABLE OPD 
ADD CONSTRAINT FK_OPD_WARD
  FOREIGN KEY (OPD_WRD_ID_A)
  REFERENCES WARD (WRD_ID_A)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

UPDATE WARD SET WRD_NQUA_NURS='4', WRD_NDOC='4' WHERE WRD_ID_A='D'; -- ward OPD
-- UPDATE WARD SET WRD_NQUA_NURS='1', WRD_NDOC='1' WHERE WRD_ID_A='D';
