-- modify OPD table

ALTER TABLE opd 
DROP FOREIGN KEY FK_OPD_DISEASE,
DROP FOREIGN KEY FK_OPD_DISEASE_2,
DROP FOREIGN KEY FK_OPD_DISEASE_3;
ALTER TABLE opd 
CHANGE COLUMN OPD_DIS_ID_A OPD_DIS_ID_A VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN OPD_DIS_ID_A_2 OPD_DIS_ID_A_2 VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN OPD_DIS_ID_A_3 OPD_DIS_ID_A_3 VARCHAR(15) NULL DEFAULT NULL ;
ALTER TABLE opd 
ADD CONSTRAINT FK_OPD_DISEASE
  FOREIGN KEY (OPD_DIS_ID_A)
  REFERENCES disease (DIS_ID_A)
  ON DELETE NO ACTION
  ON UPDATE CASCADE,
ADD CONSTRAINT FK_OPD_DISEASE_2
  FOREIGN KEY (OPD_DIS_ID_A_2)
  REFERENCES disease (DIS_ID_A)
  ON DELETE NO ACTION
  ON UPDATE CASCADE,
ADD CONSTRAINT FK_OPD_DISEASE_3
  FOREIGN KEY (OPD_DIS_ID_A_3)
  REFERENCES disease (DIS_ID_A)
  ON DELETE NO ACTION
  ON UPDATE CASCADE;


-- modify ADMISSION table
  
ALTER TABLE admission 
DROP FOREIGN KEY FK_ADMISSION_IN_DISEASE,
DROP FOREIGN KEY FK_ADMISSION_OUT_DISEASE1,
DROP FOREIGN KEY FK_ADMISSION_OUT_DISEASE2,
DROP FOREIGN KEY FK_ADMISSION_OUT_DISEASE3;
ALTER TABLE admission 
CHANGE COLUMN ADM_IN_DIS_ID_A ADM_IN_DIS_ID_A VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN ADM_OUT_DIS_ID_A ADM_OUT_DIS_ID_A VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN ADM_OUT_DIS_ID_A_2 ADM_OUT_DIS_ID_A_2 VARCHAR(15) NULL DEFAULT NULL ,
CHANGE COLUMN ADM_OUT_DIS_ID_A_3 ADM_OUT_DIS_ID_A_3 VARCHAR(15) NULL DEFAULT NULL ;
ALTER TABLE admission 
ADD CONSTRAINT FK_ADMISSION_IN_DISEASE
  FOREIGN KEY (ADM_IN_DIS_ID_A)
  REFERENCES disease (DIS_ID_A)
  ON DELETE NO ACTION
  ON UPDATE CASCADE,
ADD CONSTRAINT FK_ADMISSION_OUT_DISEASE1
  FOREIGN KEY (ADM_OUT_DIS_ID_A)
  REFERENCES disease (DIS_ID_A)
  ON DELETE NO ACTION
  ON UPDATE CASCADE,
ADD CONSTRAINT FK_ADMISSION_OUT_DISEASE2
  FOREIGN KEY (ADM_OUT_DIS_ID_A_2)
  REFERENCES disease (DIS_ID_A)
  ON DELETE NO ACTION
  ON UPDATE CASCADE,
ADD CONSTRAINT FK_ADMISSION_OUT_DISEASE3
  FOREIGN KEY (ADM_OUT_DIS_ID_A_3)
  REFERENCES disease (DIS_ID_A)
  ON DELETE NO ACTION
  ON UPDATE CASCADE;
  
-- modify MEDICALDSRWARDPRESCRIPTION table (no foreign keys because of NULL values)
ALTER TABLE medicaldsrwardprescription CHANGE COLUMN MWP_DIS_ID_A MWP_DIS_ID_A VARCHAR(15) NULL DEFAULT NULL ;
DROP TRIGGER IF EXISTS disease_AFTER_UPDATE;
DELIMITER $$
USE oh$$
CREATE DEFINER = CURRENT_USER TRIGGER disease_AFTER_UPDATE AFTER UPDATE ON disease FOR EACH ROW
BEGIN
	UPDATE MEDICALDSRWARDPRESCRIPTION SET MWP_DIS_ID_A = NEW.DIS_ID_A WHERE MWP_DIS_ID_A = OLD.DIS_ID_A;
END$$
DELIMITER ;

-- prefixing old codes and disabling 
ALTER TABLE disease CHANGE COLUMN DIS_ID_A DIS_ID_A VARCHAR(15) NOT NULL;
UPDATE DISEASE 
SET 
	DIS_ID_A = CONCAT("2016-",DIS_ID_A), 
    DIS_DESC = CONCAT("2016-",DIS_DESC),
    DIS_OPD_INCLUDE = 0,
    DIS_IPD_IN_INCLUDE = 0,
    DIS_IPD_OUT_INCLUDE = 0
WHERE 
	DIS_ID_A REGEXP '[0-9][0-9.]*[0-9]';

-- insert new EMERGENCY code (could be the existing "151 - EMERGENCY" one or a new one)
INSERT INTO DISEASE (DIS_ID_A, DIS_DESC, DIS_DCL_ID_A, DIS_LOCK, DIS_OPD_INCLUDE, DIS_IPD_IN_INCLUDE, DIS_IPD_OUT_INCLUDE, DIS_MALE, DIS_FEMALE, DIS_MIN_AGE, DIS_MAX_AGE, DIS_IS_CHRONIC) VALUES ('EM', 'EMERGENCY', '16', '0', '1', '1', '1', '1', '1', '0', '0', '0');

--
-- LOAD new diseases in DISEASE table
--
LOAD DATA LOCAL INFILE 'wolisso_step_38_HMIS_migration_script.csv' 
	INTO TABLE DISEASE 
	FIELDS TERMINATED BY ';' 
	LINES TERMINATED BY '\r\n';