START TRANSACTION;

# Insert Chronic OPD button item in MENUITEM table
INSERT INTO MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION)
VALUES ('btnchropd', 'angal.opdchronic.registration', 'angal.opdchronic.registration', 'x', 'K', 'opd',
        'none', 'N', '7');

# Add Chronic OPD Physician user group
INSERT INTO USERGROUP (UG_ID_A, UG_DESC) VALUES ('Chronic OPD Physician', 'Physician working in Chronic OPD Room');

# Add 'btnchropd' permission to GROUPMENU table
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin', 'btnchropd', 'Y');
INSERT INTO GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('Chronic OPD Physician', 'btnchropd', 'Y');

# Add IS_CHRONIC, OPD_SCHEDULED_DATE, OPD_NEXT_VISIT_DATE columns to OPD table
ALTER TABLE OPD ADD COLUMN `OPD_IS_CHRONIC` TINYINT NULL DEFAULT 0 AFTER `OPD_LOCK`;
ALTER TABLE OPD ADD OPD_SCHEDULED_VISIT_ID INT(11) NULL;
ALTER TABLE OPD ADD OPD_NEXT_VISIT_ID INT(11) NULL;
ALTER TABLE OPD ADD OPD_US_ID_A VARCHAR(32) NULL;

ALTER TABLE OPD 
ADD INDEX FK_OPD_NEXT_VISIT_IDX (OPD_NEXT_VISIT_ID ASC),
ADD INDEX FK_OPD_SCHED_VISIT_IDX (OPD_SCHEDULED_VISIT_ID ASC),
ADD INDEX FK_OPD_USER_IDX (OPD_US_ID_A ASC);

ALTER TABLE OPD 
ADD CONSTRAINT FK_OPD_NEXT_VISIT FOREIGN KEY (OPD_NEXT_VISIT_ID) REFERENCES VISITS (VST_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT FK_OPD_SCHED_VISIT FOREIGN KEY (OPD_SCHEDULED_VISIT_ID) REFERENCES VISITS (VST_ID) ON DELETE NO ACTION ON UPDATE NO ACTION, 
ADD CONSTRAINT FK_OPD_USER FOREIGN KEY (OPD_US_ID_A) REFERENCES USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION;

# Create table OPD_CHRONIC
DROP TABLE IF EXISTS OPD_CHRONIC;
CREATE TABLE OPD_CHRONIC
(
        CV_ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        CV_OPD_ID INT,
        CV_DATE_CREATED DATETIME,
        CV_LAST_UPDATED DATETIME,
        CV_DISEASE_CODES VARCHAR(32),
        CV_BW INT,
        CV_FBS INT,
        CV_CREATININE DOUBLE,
        CV_BP_MIN INT,
        CV_BP_MAX INT,
        CV_AF BOOLEAN,
        CV_HR INT,
        CV_HB DECIMAL(7,2),
        CV_CF VARCHAR(256),
        CV_PO2 INT,
        CV_NOTES VARCHAR(512)
);

ALTER TABLE OPD_CHRONIC 
ADD INDEX FK_OPD_CHRONIC_OPD_IDX (CV_OPD_ID ASC);

ALTER TABLE OPD_CHRONIC 
ADD CONSTRAINT FK_OPD_CHRONIC_OPD FOREIGN KEY (CV_OPD_ID) REFERENCES OPD (OPD_ID) ON DELETE CASCADE ON UPDATE CASCADE;


# Add THR_QTY_2, THR_QTY_3, THR_QTY_4, THR_OPD_CODE, THR_DATE_DELETED to THERAPIES table
ALTER TABLE THERAPIES ADD THR_QTY_2 DOUBLE NULL;
ALTER TABLE THERAPIES ADD THR_QTY_3 DOUBLE NULL;
ALTER TABLE THERAPIES ADD THR_QTY_4 DOUBLE NULL;
ALTER TABLE THERAPIES ADD THR_OPD_ID INT NULL;
ALTER TABLE THERAPIES ADD THR_DATE_DELETED DATETIME DEFAULT NULL NULL;

# Add MWP_OPD_ID to MEDICALDSRWARDPRESCRIPTION table
ALTER TABLE MEDICALDSRWARDPRESCRIPTION ADD MWP_OPD_ID INT(11) NULL;

# Add DIS_IS_CHRONIC field to DISEASE table
ALTER TABLE DISEASE ADD DIS_IS_CHRONIC TINYINT DEFAULT 0 NULL;

# Set DIS_IS_CHRONIC for all chronic diseases
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '044';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '045';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '046';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '047';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '048';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '049';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '050';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '051';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '052';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '053';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '054';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '055.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '055.2';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '056.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '056.2';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '057.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '057.2';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '057.3';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '057.4';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '058';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '058.01';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '058.011';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '058.012';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '058.02';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '058.021';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '058.022';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '059';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '063.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '063.11';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '063.12';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '063.2';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '065.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '065.3';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '065.4';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '065.41';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '066.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '066.22';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '067';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '068';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '069';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '070';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '072';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '073';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '075.3';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '076';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '080';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '080.01';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '080.02';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '080.03';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '080.04';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '081';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.2';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.3';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.31';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.32';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.33';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.34';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.35';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.36';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.37';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '082.38';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '083';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '084';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '084.01';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '085';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '086';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '086.01';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '093';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '093.01';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '093.02';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '097.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '104.3';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '105.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '105.2';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '106.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '107.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '107.2';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '109';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '109.01';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '112';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '122';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '123';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '124';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '125';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '126.1';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '127';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '128';
UPDATE DISEASE SET DIS_IS_CHRONIC = 1 WHERE DIS_ID_A = '129';

COMMIT;
