DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER (
	SUP_ID INT(11) NOT NULL AUTO_INCREMENT,
	SUP_NAME VARCHAR(100) NULL,
	SUP_ADDRESS VARCHAR(150) NULL,
	SUP_TAXCODE VARCHAR(50) NULL,
	SUP_PHONE VARCHAR(20) NULL,
	SUP_FAX VARCHAR(20) NULL,
	SUP_EMAIL VARCHAR(100) NULL,
	SUP_NOTE VARCHAR(200) NULL,
	SUP_DELETED char(1) DEFAULT 'N',
	PRIMARY KEY (SUP_ID)
);

--
-- Dump SUPPLIER table
--
LOAD DATA LOCAL INFILE 'wolisso_step_01_suppliers.csv' 
	INTO TABLE SUPPLIER 
	FIELDS TERMINATED BY ';' 
	LINES TERMINATED BY '\r\n';