SELECT a.*, "discharge" AS MLN_TYPE_DIS,
	(SELECT MLN_DATE_VIS
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_DATE_VIS_DIS,
	(SELECT MLN_HEIGHT
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_HEIGHT_DIS,
    (SELECT MLN_WEIGHT
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_WEIGHT_DIS,
    (SELECT MLN_MUAC
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_MUAC_DIS,
    (SELECT MLN_WH
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_WH_DIS,
    (SELECT MLN_MIN_WEIGHT
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_MIN_WEIGHT_DIS,
    (SELECT MLN_MIN_WEIGHT_DATE
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_MIN_WEIGHT_DATE_DIS,
    (SELECT MLN_TB
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_TB_DIS,
    (SELECT MLN_HIV
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_HIV_DIS,
   (SELECT MLN_SEPSIS
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_SEPSIS_DIS,
    (SELECT MLN_ANAEMIA
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_ANAEMIA_DIS,
    (SELECT MLN_PNEUMONIA
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_PNEUMONIA_DIS,
    (SELECT MLN_MALARIA
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_MALARIA_DIS,
    (SELECT MLN_CP
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_CP_DIS,
    (SELECT MLN_RICKETTS
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_RICKETTS_DIS,
    (SELECT MLN_OTHER
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_OTHER_DIS,
    (SELECT MLN_REMARKS
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_REMARKS_DIS,
    (SELECT MLN_OUTCOME
    FROM MALNUTRITIONCONTROL b
	WHERE MLN_TYPE = 'discharge'
    AND a.MLN_ADM_ID = b.MLN_ADM_ID) AS MLN_OUTCOME_DIS

FROM MALNUTRITIONCONTROL a
WHERE a.MLN_TYPE = 'admission'
ORDER BY a.MLN_ADM_ID