select ADM_ID, 
    MWP_ID, 
    ADM_PAT_ID, 
    (SELECT MDSR_DESC FROM MEDICALDSR WHERE MDSR_ID = MWPD_MDSR_ID) AS MDSR_DESCRIP,
    MWP_DATE,
    (SELECT WRD_NAME FROM WARD WHERE WRD_ID_A = MWP_WRD_ID_A) AS WARD_NAME,
    MWP_BLL_ID, 
    (SELECT DIS_DESC FROM DISEASE WHERE DIS_ID_A = MWP_DIS_ID_A) AS ADM_DISEASE_PRESC,
    ADM_DATE_ADM,
    (SELECT ADMT_DESC FROM ADMISSIONTYPE WHERE ADMT_ID_A = ADM_ADMT_ID_A_ADM) AS AD_TYPE,
    (SELECT DIS_DESC FROM DISEASE WHERE DIS_ID_A = ADM_IN_DIS_ID_A)    AS ADM_DISEASE,
    (SELECT DIS_DESC FROM DISEASE WHERE DIS_ID_A = ADM_OUT_DIS_ID_A)   AS OUT_DISEASE1,
    (SELECT DIS_DESC FROM DISEASE WHERE DIS_ID_A = ADM_OUT_DIS_ID_A_2) AS OUT_DISEASE2,
    (SELECT DIS_DESC FROM DISEASE WHERE DIS_ID_A = ADM_OUT_DIS_ID_A_3) AS OUT_DISEASE3,
    ADM_DATE_DIS, 
    ( SELECT DIST_DESC FROM DISCHARGETYPE WHERE DIST_ID_A = ADM_DIST_ID_A ) AS DISCHARGE_TYPE,
    ( SELECT PRS_NAME FROM PRESCRIBER WHERE PRS_ID = MWP_PRS_ID ) AS DOCTOR
from 
MEDICALDSR
join(
    select ADM_ID, MWP_ID, ADM_PAT_ID, MWPD_MDSR_ID, MWP_DATE, MWP_WRD_ID_A, MWP_BLL_ID, MWP_DIS_ID_A, MWP_PRS_ID,
            ADM_DATE_ADM, ADM_ADMT_ID_A_ADM, ADM_IN_DIS_ID_A, ADM_OUT_DIS_ID_A, ADM_OUT_DIS_ID_A_2, ADM_OUT_DIS_ID_A_3,
            ADM_DATE_DIS, ADM_DIST_ID_A
    from MEDICALDSRWARDPRESCRIPTIONDETAIL
    join (
        select ADM_ID, MWP_ID, ADM_PAT_ID, MWP_DATE, MWP_WRD_ID_A, MWP_BLL_ID, MWP_DIS_ID_A, MWP_PRS_ID,
                ADM_DATE_ADM, ADM_ADMT_ID_A_ADM, ADM_IN_DIS_ID_A, ADM_OUT_DIS_ID_A, ADM_OUT_DIS_ID_A_2, ADM_OUT_DIS_ID_A_3,
                ADM_DATE_DIS, ADM_DIST_ID_A
        from MEDICALDSRWARDPRESCRIPTION
        join (
            select ADM_ID, ADM_PAT_ID, ADM_DATE_ADM, ADM_ADMT_ID_A_ADM, ADM_IN_DIS_ID_A, ADM_OUT_DIS_ID_A, ADM_OUT_DIS_ID_A_2, 
                ADM_OUT_DIS_ID_A_3, ADM_DATE_DIS, ADM_DIST_ID_A 
            from ADMISSION
            WHERE DATE_FORMAT(ADM_DATE_DIS, '%Y-%m-&d') >= '2014-01-01' and DATE_FORMAT(ADM_DATE_DIS, '%Y-%m-&d') <= '2014-07-01' 
                and ADM_DATE_DIS != 'NULL' AND ADM_DELETED='N'
        ) as B
        on MWP_PAT_ID=ADM_PAT_ID and MWP_DATE >= ADM_DATE_ADM and MWP_DATE <= ADM_DATE_DIS
        order by ADM_ID, MWP_ID, ADM_PAT_ID
    ) as C
    on MWPD_ID = MWP_ID
)as D
on MWPD_MDSR_ID=MDSR_ID