select PAT_ID, PAT_CITY, PAT_BDATE, PAT_AGE, PAT_SEX, ADM_ID,
 ADM_TYPE,
 ADM_DATE_ADM, 
 (SELECT ADMT_DESC FROM ADMISSIONTYPE WHERE ADMT_ID_A = ADM_ADMT_ID_A_ADM) AS AD_TYPE, 
 (SELECT WRD_NAME FROM WARD WHERE WRD_ID_A = ADM_WRD_ID_A) AS WARD_NAME,
 ADM_PATOLOGY,
 DIS_DESC as DISC_PATOLOGY, 
 OUT_D, 
 ADM_DATE_DIS, 
 ( SELECT DIST_DESC FROM DISCHARGETYPE WHERE DIST_ID_A = ADM_DIST_ID_A ) AS DISCHARGE_TYPE
from(
    select PAT_ID, PAT_CITY, PAT_BDATE, PAT_AGE, PAT_SEX, ADM_ID, ADM_TYPE, ADM_DATE_ADM, ADM_ADMT_ID_A_ADM, DIS_DESC as ADM_PATOLOGY,
        ADM_OUT_DIS_ID_A as out_dismis, 1 as OUT_D,  ADM_DATE_DIS, ADM_DIST_ID_A, ADM_WRD_ID_A
    from ADMISSION join PATIENT on ADM_PAT_ID=PAT_ID 
    join DISEASE 
    on DIS_ID_A=ADM_IN_DIS_ID_A 
    WHERE ADM_DATE_ADM >= '2014-06-01' 
        AND ADM_DATE_ADM <= '2014-07-04' and ADM_DELETED='N' and ADM_DATE_DIS <= '2014-07-01' 
    union
    select PAT_ID, PAT_CITY, PAT_BDATE, PAT_AGE, PAT_SEX, ADM_ID, ADM_TYPE, ADM_DATE_ADM, ADM_ADMT_ID_A_ADM, DIS_DESC as ADM_PATOLOGY,
            ADM_OUT_DIS_ID_A_2 as out_dismis, 2 as OUT_D, ADM_DATE_DIS, ADM_DIST_ID_A, ADM_WRD_ID_A
    from ADMISSION 
    join PATIENT 
    on ADM_PAT_ID=PAT_ID 
    join DISEASE 
    on DIS_ID_A=ADM_IN_DIS_ID_A 
    WHERE ADM_DATE_ADM >= '2014-06-01' 
        AND ADM_DATE_ADM <= '2014-07-04' and ADM_DELETED='N' and ADM_DATE_DIS <= '2014-07-01'
    union 
    select PAT_ID, PAT_CITY, PAT_BDATE, PAT_AGE, PAT_SEX, ADM_ID, ADM_TYPE, ADM_DATE_ADM, ADM_ADMT_ID_A_ADM, DIS_DESC as ADM_PATOLOGY,
        ADM_OUT_DIS_ID_A_3 as out_dismis, 3 as OUT_D, ADM_DATE_DIS, ADM_DIST_ID_A, ADM_WRD_ID_A
    from ADMISSION 
    join PATIENT 
    on ADM_PAT_ID=PAT_ID 
    join DISEASE 
    on DIS_ID_A=ADM_IN_DIS_ID_A 
    WHERE ADM_DATE_ADM >= '2014-06-01' 
        AND ADM_DATE_ADM <= '2014-07-04' and ADM_DELETED='N' and ADM_DATE_DIS <= '2014-07-01'
    ) as t
join DISEASE 
on DIS_ID_A=out_dismis
